### PR TITLE
Fixed blank author bug. Also formatted using ESlint/prettier

### LINKED ISSUE #47: Github container failing when commit author is anonymous
`author` can appear blank for `singleCommit` when someone commits without valid github user email setup in the github config.

Error message:
```
github            | /usr/src/app/service.js:65
github            |                         singleCommit.author.date = time.toLocaleString("en-US", {timeZone : "America/Toronto"});
github            |                                                  ^
github            | 
github            | TypeError: Cannot set property 'date' of null
github            |     at /usr/src/app/service.js:65:50
github            |     at Array.forEach (<anonymous>)
github            |     at Request._callback (/usr/src/app/service.js:61:34)
github            |     at Request.self.callback (/usr/src/app/node_modules/request/request.js:185:22)
github            |     at Request.emit (events.js:196:13)
github            |     at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1161:10)
github            |     at Request.emit (events.js:196:13)
github            |     at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:1083:12)
github            |     at Object.onceWrapper (events.js:284:20)
github            |     at IncomingMessage.emit (events.js:201:15)
github            | npm ERR! code ELIFECYCLE
github            | npm ERR! errno 1
github            | npm ERR! github-server@1.0.0 start: `node server.js`
github            | npm ERR! Exit status 1
github            | npm ERR! 
github            | npm ERR! Failed at the github-server@1.0.0 start script.
github            | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
github            | 
github            | npm ERR! A complete log of this run can be found in:
github            | npm ERR!     /root/.npm/_logs/2019-05-23T22_08_28_057Z-debug.log

```

### PR DESCRIPTION
**Pull request by manekenpix**
Closes #47

### CODE REVIEW

File: Github/service.js [hunk 1]
```diff
@@ -1,134 +1,164 @@
...
+            if (
+              new Date(today - new Date(singleCommit.commit.author.date)) <
+              new Date(recency)
+            ) {
+              const time = new Date(singleCommit.commit.author.date);
+              singleCommit.author = {
+                name: singleCommit.commit.author.name,
+                date: time.toLocaleString('en-US', {
+                  timeZone: 'America/Toronto',
+                }),
```
Comment (manekenpix) [inline Github/service.js]: This is what I changed:
```
singleCommit.author.date = time.toLocaleString("en-US", {timeZone : "America/Toronto"});
singleCommit.author.name = singleCommit.commit.author.name;
```
and now it's what is in lines 82 to 86

File: Github/service.js [hunk 2]
```diff
@@ -1,134 +1,164 @@
...
+      (err, res, data) => {
+        if (err) {
+          console.log('Error:', err);
+          reject(new Error(`Unable to get repos.`));
+        } else {
+          const reposX = JSON.parse(data);
+          reposX.forEach(repo => {
+            repo.branches_url = repo.branches_url.slice(
+              0,
+              repo.branches_url.length - 9,
```
Comment (belavina) [inline Github/service.js]: Not very clear what number 9 means in this case, could probably replace the slice statement with `repo.branches_url.substr(0, repo.branches_url.indexOf('{/branch}'))`
See https://eslint.org/docs/rules/no-magic-numbers

File: Github/service.js [hunk 3]
```diff
@@ -1,134 +1,164 @@
...
-                    }
-                });
-                resolve();
+  return new Promise((resolve, reject) => {
+    request.get(
+      {
+        url: repoUrl,
+        headers: { 'User-Agent': 'request' },
+      },
+      (err, res, data) => {
```
Comment (belavina) [inline Github/service.js]: In the future we will need filter out Error Status codes (non 20X) since these bypass if (err) {..} statement.
E.g. I ran into this issue today when github auth token got invalidated somehow and 401 was returned & resulted in ambiguous errors. I think I am going to open a separate issue for this since it's unrelated to this PR.

File: Github/service.js [hunk 4]
```diff
@@ -1,134 +1,164 @@
...
+        if (err) {
+          console.log('Error:', err);
+          reject(err);
+        } else {
+          JSON.parse(data).forEach(singleCommit => {
+            if (
+              new Date(today - new Date(singleCommit.commit.author.date)) <
+              new Date(recency)
```
Comment (poftadeh) [inline Github/service.js]: We can improve this. Subtracting two Date objects results in a number which means we don't have to wrap it in another Date object nor do we need to convert recency to a Date. i.e.

`if ( today - new Date(author.date) < recency)`
